# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      electron-forge:
        patterns:
          - '@electron-forge/*'
      eslint:
        patterns:
          - eslint
          - '@eslint/*'
      stylelint:
        patterns:
          - stylelint*
    labels:
      - 'electron'
      - 'ignore-for-release'
  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      boto3:
        patterns:
          - boto3
          - boto3-stubs
      requests:
        patterns:
          - requests
          - types-requests
    labels:
      - 'data'
      - 'ignore-for-release'
