name: Data

on:
    schedule:
        - cron: '0 8 * * *'
    workflow_dispatch:

jobs:

    generate:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                league: [challenge, challengehc, standard, hardcore]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt

            - name: Generate data for ${{ matrix.league }}
              env:
                DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              run: python -m data gen ${{ matrix.league }}

            - name: Shelf data file
              uses: actions/upload-artifact@v4
              with:
                name: data-files-${{ matrix.league }}
                path: data-${{ matrix.league }}.json

    publish:
        runs-on: ubuntu-latest
        needs: generate
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt

            - name: Unshelf data files
              uses: actions/download-artifact@v4
              with:
                  pattern: data-files-*
                  merge-multiple: true

            - name: Publish all data files
              env:
                AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
                S3_PUBLIC_BUCKET: ${{ secrets.S3_PUBLIC_BUCKET }}
                CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
              run: |
                  python -m data pub data-*.json
